name: Security scans for TS apps

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-and-scan-with-trivy:
    contents: read
    security-events: write
  name: Build and scan
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Build image from Dockerfile
      run: |
        docker build -t ${{ inputs.image-tag }}
    - name: Run trivy vulnerability scanner
      uses: aquasecurity/trivy-action@b2933f565dbc598b29947660e66259e3c7bc8561
      with:
        image-ref: '${{ inputs.image-tag }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
    - name: Upload Trivy scan results to Github Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'


