name: Security scans for TS apps

on:
  workflow_call:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  IMAGE_TAG: security-build:${{ github.sha }}

jobs:
  build-and-scan-with-trivy:
    permissions:
      contents: read
      security-events: write
    name: Build and scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image from Dockerfile
        run: |
          docker build . -t ${{ env.IMAGE_TAG }}
      - name: Run trivy vulnerability scanner and print output
        uses: aquasecurity/trivy-action@595be6a0f6560a0a8fc419ddf630567fc623531d
        with:
          image-ref: '${{ env.IMAGE_TAG }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
      - name: Run trivy vulnerability scanner and generate sarif output
        uses: aquasecurity/trivy-action@595be6a0f6560a0a8fc419ddf630567fc623531d
        with:
          image-ref: '${{ env.IMAGE_TAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - run: |
          sed -i "s/library\/security-build/Dockerfile/g" trivy-results.sarif
          sed -i "s/\"endLine\": 1/\"endLine\":$(sed -n '$=' Dockerfile)/g" trivy-results.sarif
          tail -n 1000 trivy-results.sarif
        if: always()
      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'


