name: Security scans for TS apps

on:
  workflow_call:

permissions:
  contents: read

env:
  IMAGE_TAG: ${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-scan-with-trivy:
    permissions:
      contents: read
      security-events: write
    name: Build and scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image from Dockerfile
        run: |
          docker build . -t ${{ env.IMAGE_TAG }}
      - name: Run trivy vulnerability scanner
        uses: aquasecurity/trivy-action@b2933f565dbc598b29947660e66259e3c7bc8561
        with:
          image-ref: '${{ env.IMAGE_TAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'


